language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO="django>=2.0,<=3.2"
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django>=1.7,<=1.11"
    - python: "3.3"
      env: DJANGO="django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="django>=1.10,<2.0"
    - python: "3.5"
      env: DJANGO="django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO="django>=1.7,<1.8"
install:
  - "pip install ."
  - "pip install ${DJANGO}"
script:
  - "python manage.py test"
