# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 03:25
from __future__ import unicode_literals, print_function
import os
import csv

from django.db import migrations, models
import django.db.models.deletion

CSV_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'csv'))


def populate_provinces(apps, schema_editor):
    print('\n\n  Populating provinces...')
    with open(os.path.join(CSV_PATH, 'provinces.csv'), 'rb') as provinces:
        reader = csv.reader(provinces, delimiter=b',')
        for i in reader:
            print(i)


def populate_regencies(apps, schema_editor):
    print('  Populating regencies...')
    with open(os.path.join(CSV_PATH, 'regencies.csv'), 'rb') as regencies:
        reader = csv.reader(regencies, delimiter=b',')
        for i in reader:
            print(i)


def populate_districts(apps, schema_editor):
    print('  Populating districts...')
    with open(os.path.join(CSV_PATH, 'districts.csv'), 'rb') as disticts:
        reader = csv.reader(disticts, delimiter=b',')
        for i in reader:
            print(i)


def populate_villages(apps, schema_editor):
    print('  Populating villages...')
    print('  DONE.')
    with open(os.path.join(CSV_PATH, 'villages.csv'), 'rb') as villages:
        reader = csv.reader(villages, delimiter=b',')
        for i in reader:
            print(i)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district_id', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province_id', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regency_id', models.CharField(max_length=80, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djindonesiaregions.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('village_id', models.CharField(max_length=80, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djindonesiaregions.District')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='regency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djindonesiaregions.Regency'),
        ),
        migrations.RunPython(populate_provinces),
        migrations.RunPython(populate_regencies),
        migrations.RunPython(populate_districts),
        migrations.RunPython(populate_villages),
    ]
